apiVersion: v1
kind: Service
metadata:
  name: {{ include "context7-mcp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "context7-mcp.name" . }}
    helm.sh/chart: {{ include "context7-mcp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "context7-mcp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
